### ISSUE TITLE
Can I have a chat with you?

### ISSUE THREAD

**Issue by dreemhai** [Tony133/nestjs-mongodb-driver#298]
Dear Antonio Tripodi
I have an interesting crypto based game project and currently looking for a senior developer who can help me.
Can we have a little chat?

dreemhai#9292
This is my discord id, please send me a message.
Looking forward to talking with you.
Thanks

**Comment by Tony133** [comment]
Dear @dreemhai,
Thank you for the proposal but unfortunately I am currently busy with some projects and I don't know when I will be free.

Thank you very much again for the proposal 🙏🏻

Best regards

Antonio Tripodi

**Comment by dreemhai** [comment]
@Tony133 thanks for your reply.
okay, then I will close this issue. Good luck with your work!
